export const areas = [
    {text: 'United States of America', code: 'US'}, 
    {text: 'Canada', code: 'CA'}, 
    {text: 'United Kingdom of Great Britain', code: 'GB'}, 
    {text: 'Afghanistan', code: 'AF'}, 
    {text: 'Albania', code: 'AL'}, 
    {text: 'Algeria', code: 'DZ'}, 
    {text: 'American Samoa', code: 'AS'}, 
    {text: 'Andorra', code: 'AD'},
    {text: 'Angola', code: 'AO'},
    {text: 'Anguilla', code: 'AI'},
    {text: 'Antartica', code: 'AQ'},
    {text: 'Antingua and Barbuda', code: 'AG'},     
    {text: 'Argentina', code: 'AR'}, 
    {text: 'Armenia', code: 'AM'},
    {text: 'Aruba', code: 'AW'},
    {text: 'Australia', code: 'AU'},
    {text: 'Austria', code: 'AT'},
    {text: 'Azerbaijan', code: 'AZ'},     
    {text: 'Bahamas', code: 'BS'},
    {text: 'Bahrain', code: 'BH'},
    {text: 'Bangladesh', code: 'BD'},
    {text: 'Barbados', code: 'BB'},    
    {text: 'Belarus', code: 'BY'},
    {text: 'Belgium', code: 'BE'},  
    {text: 'Belize', code: 'BZ'}, 
    {text: 'Benin', code: 'BJ'},
    {text: 'Bermuda', code: 'BM'},
    {text: 'Bhutan', code: 'BT'},
    {text: 'Bolivia', code: 'BO'},
    {text: 'Bonnaire, Sint Eustatius and Saba', code: 'BQ'},    
    {text: 'Bosnia and Herzegovina', code: 'BA'},
    {text: 'Botswana', code: 'BW'},
    {text: 'Bouvet Island', code: 'BV'},
    {text: 'Brazil', code: 'BR'},
    {text: 'British Indian Ocean Territory', code: '\IO'},
    {text: 'Brunei Darussalam', code: 'BN'},
    {text: 'Bulgaria', code: 'BG'},
    {text: 'Burkina Faso', code: 'BF'},
    {text: 'Burundi', code: 'BI'},
    {text: 'Cabo Verde', code: 'CV'},
    {text: 'Cambodia', code: 'KH'},
    {text: 'Cameroon', code: 'CM'},
    {text: 'Cayman Islands', code: 'KY'},
    {text: 'Central African Republic', code: 'CF'},
    {text: 'Chad', code: 'CL'},
    {text: 'Chile', code: 'TD'},
    {text: 'China', code: 'CN'},
    {text: 'Christmas Island', code: 'CX'},
    {text: 'Cocos (Keeling) Islands', code: 'CC'},
    {text: 'Colombia', code: 'CO'},
    {text: 'Comoros', code: 'KM'},
    {text: 'Congo', code: 'CG'},
    {text: 'Cook Islands', code: 'CK'},
    {text: 'Costa Rica', code: 'CR'},
    {text: 'Croatia', code: 'HR'},
    {text: 'Cuba', code: 'CU'},
    {text: 'Curacao', code: 'CW'},
    {text: 'Cyprus', code: 'CY'},
    {text: 'Czechia', code: 'CZ'},
    {text: "Cote d'lvoire", code: 'CI'},
    {text: 'Denmark', code: 'DK'},
    {text: 'Djibouti', code: 'DJ'},
    {text: 'Dominican Republic', code: 'DO'},
    {text: 'Ecuador', code: 'EC'},               
    {text: 'Egypt', code: 'EG'},               
    {text: 'El Salvador', code: 'SV'},
    {text: 'Equatorial Guinea', code: 'GQ'},               
    {text: 'Eritrea', code: 'ER'},               
    {text: 'Estonia', code: 'EE'},               
    {text: 'Eswatini', code: 'SZ'},
    {text: 'Ethiopia', code: 'ET'},               
    {text: 'Falkland Islands', code: 'FK'},
    {text: 'Faroe Islands', code: 'FO'},
    {text: 'Fiji', code: 'FJ'},               
    {text: 'Finland', code: 'FI'},
    {text: 'France', code: 'FR'},
    {text: 'French Guiana', code: 'GF'},
    {text: 'French Polynesia', code: 'PF'},
    {text: 'French Southern Territories', code: 'TF'},
    {text: 'Gabon', code: 'GA'},
    {text: 'Gambia', code: 'GM'},
    {text: 'Georgia', code: 'GE'},
    {text: 'Germany', code: 'DE'},  
    {text: 'Ghana', code: 'GH'},
    {text: 'Gibraltar', code: 'GI'},
    {text: 'Greece', code: 'GR'},
    {text: 'Greenland', code: 'GL'},
    {text: 'Grenada', code: 'GD'},
    {text: 'Guadeloupe', code: 'GP'},
    {text: 'Guam', code: 'GU'},
    {text: 'Guatemala', code: 'GT'},
    {text: 'Guernsey', code: 'GG'},
    {text: 'Guinea', code: 'GN'},
    {text: 'Guinea-Bissau', code: 'GW'},
    {text: 'Guyana', code: 'GY'},
    {text: 'Haiti', code: 'HT'},
    {text: 'Heard Island and McDonald Islands', code: 'HM'},
    {text: 'Holy See', code: 'VA'},
    {text: 'Honduras', code: 'HN'},
    {text: 'Hong Kong', code: 'HK'},
    {text: 'Hungary', code: 'HU'},
    {text: 'Iceland', code: 'IS'},
    {text: 'India', code: 'IN'},
    {text: 'Indonesia', code: 'ID'},
    {text: 'Iran', code: 'IR'},
    {text: 'Iraq', code: 'IQ'},
    {text: 'Ireland', code: 'IE'},
    {text: 'Isle of Man', code: 'IM'},
    {text: 'Israel', code: 'IL'},
    {text: 'Italy', code: 'IT'},
    {text: 'Jamaica', code: 'JM'},
    {text: 'Japan', code: 'JP'},
    {text: 'Jersey', code: 'JE'},
    {text: 'Jordan', code: 'JO'},
    {text: 'Kazakhstan', code: 'KZ'},
    {text: 'Kenya', code: 'KE'},
    {text: 'Kiribati', code: 'KI'},
    {text: "North Korea", code: 'KP'},
    {text: 'South Korea', code: 'KR'},
    {text: 'Kuwait', code: 'KW'},
    {text: 'Kyrgyzstan', code: 'KG'},
    {text: "Lao People's Democratic Republic (the)", code: 'LA'},
    {text: 'Latvia', code: 'LV'},
    {text: 'Lebanon', code: 'LB'},
    {text: 'Lesotho', code: 'LS'},
    {text: 'Liberia', code: 'LR'},
    {text: 'Libya', code: 'LY'},
    {text: 'Liechtenstein', code: 'LI'},
    {text: 'Lithuania', code: 'LT'},
    {text: 'Luxembourg', code: 'LU'},
    {text: 'Macao', code: 'MO'},
    {text: 'Madagascar', code: 'MG'},
    {text: 'Malawi', code: 'MW'},
    {text: 'Malaysia', code: 'MY'},
    {text: 'Maldives', code: 'MV'},
    {text: 'Mali', code: 'ML'},
    {text: 'Malta', code: 'MT'},
    {text: 'Marshall Islands', code: 'MH'},
    {text: 'Martinique', code: 'MQ'},
    {text: 'Mauritania', code: 'MR'},
    {text: 'Mauritius', code: 'MU'},
    {text: 'Mayotte', code: 'YT'},
    {text: 'Mexico', code: 'MX'},
    {text: 'Micronesia', code: 'FM'},
    {text: 'Moldova', code: 'MD'},
]